# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    dmidecode
    free -m
    df -h
    cat /etc/os-release
  displayName: 'Execute dmidecode and a some other diagnostic commands'
  
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
